<script type="text/x-magento-init">
{
    "#telephone": {
        "TheITNerd_UX/js/inputMask": {
            "mask": "(00) 0000-00000"
        }
    },
    "#postcode": {
        "TheITNerd_UX/js/inputMask": {
            "mask": "00000-000"
        }
    },
    "#vat_tax_id": {
        "TheITNerd_UX/js/cpfCnpjField": {
            "cnpj": true,
            "cpf": false
        }
    }
}
</script>
