<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
/** @var \TheITNerd\UX\Helper\Data $helper */
$helper = $this->helper(\TheITNerd\UX\Helper\Data::class);

?>
<div class="block newsletter">
    <div class="title"><strong><?= $block->escapeHtml(__('Newsletter')) ?></strong></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <div class="control">
                    <label for="newsletter">
                        <span class="label">
                            <?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?>
                        </span>
                        <input name="email" type="email" id="newsletter"
                               placeholder="<?= $block->escapeHtml(__('Enter your email address')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}"
                        />
                    </label>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary"
                        title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                        type="submit"
                        aria-label="Subscribe">
                    <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                </button>
            </div>
            <?php if($helper->getNewsletterPrivacyPolicyStatus()): ?>
            <div class="field terms">
                <div class="control">
                    <label><input type="checkbox" value="1" name="privacy_policy" id="newsletter_privacy_policy" data-validate="{required:true}" class="required-entry"> <?= __('Please accept our <a href="javascript:void(0)" data-trigger="newsletter_privacy_policy_modal"> terms & conditions</a>') ?></label>
                </div>
            </div>
            <?php endif; ?>
        </form>
    </div>
</div>
<?php if($helper->getNewsletterPrivacyPolicyStatus()): ?>
<div id="newsletter_privacy_policy_modal" style="display: none">
    <?= $helper->getNewsletterPrivacyPolicyText(); ?>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "newsletter-validate-detail"
            }
        }<?php if($helper->getNewsletterPrivacyPolicyStatus()): ?> ,
        "#newsletter_privacy_policy_modal" : {
            "Magento_Ui/js/modal/modal" :{
                "type": "popup",
                "title": "<?= __('Newsletter Privacy Policy') ?>",
                "trigger": "[data-trigger=newsletter_privacy_policy_modal]",
                "responsive": true,
                "buttons": []
            }
        }
        <?php endif; ?>
    }
</script>
